---
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Topics"
subtitle: ""
summary: ""
authors: []
tags: []
categories: []
date: 
lastmod: 2020-09-11T11:17:19-07:00
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

   • **Block 1** – Current progress & challenges in Earth system research (atmosphere-hydrosphere- biosphere);
   
   • **Block 2** – Modelling (Earth system, numerical weather prediction, atmospheric chemical transport, seamless online integrated, atmospheric boundary layer) and specific challenges;
   
   • **Block 3** – Chemistry (gas, liquid) and aerosols (properties, dynamics, chemistry, micro-physics, interactions);
   
   • **Block 4** – Emissions, data assimilation, models evaluation;
   
   • **Block 5** – Ground-based and remote sensing observations; EU and Russian strategies for hydro-meteorological, ecosystems and atmospheric composition monitoring; SMEAR stations; measurements for atmospheric composition, ecosystems, meteorological, hydrological, urban scale;
   
   • **Block 6** - GIS technologies in environmental sciences; Environmental (land, water, terrestrial ecosystems) and human health assessments.
   
   **& Practical Exercises as Small-Scale Research Projects (SSRP)** on selected research topics to be accomplished by groups of students led by teachers
