---
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "MEGAPOLIS2022 Commitment to Diversity, Equity and Inclusion"
subtitle: ""
summary: ""
authors: []
tags: []
categories: []
date: 
lastmod: 2022-09-11T11:17:19-07:00
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

As defined in the AGU 2018 Diversity and Inclusion Strategic Plan’s vision, “Diversity and inclusion are recognized and celebrated as being essential for the success of AGU, its members, and the global Earth and space science enterprise.” At *Megapolis2022*, we value diversity, which we define as both visible and invisible differences in social and cultural identities, which inform our educational experiences and consequently influence our research and scientific accomplishments. Further, we value inclusion and work to incorporate people from all backgrounds and experiences in a way that shows respect. We embrace multiculturalism and want to acknowledge and include values and differences into our conference, in a professional manner. Finally, we value equity, which means that we understand that different social groups have not started from the same places.  We will work to help, in particular those who have not had the same advantages as others. The organizers and participants in this conference are committed to these values and continuing to learn and educate ourselves to improve scientific and DE&I outcomes better.
