---
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Timetable"
subtitle: '<a href="/media/2022Megapolis_SCHEDULE_14Nov.pdf" target="_blank" rel="noopener"><i class="fas fa-download"></i> Download .pdf version </a> <br> <i class="fas fa-clock"></i> Moscow time'
summary: ""
authors: []
tags: []
categories: []
date: 
lastmod: 2022-09-11T11:17:19-07:00
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---


| 1st December |||Video|Files|
|----------|:-------------|------------------:|--:|--:|
| 16:30 |    |  Opening ceremony|||
| 16:45 |  **[Ivan Lizaga](/authors/lizaga/)**  |  Past, present and future of sediment fingerprinting| **[<i class="fab fa-youtube"></i>](https://youtu.be/0dIsyDPPoV4)** | **[<i class="fab fa-google-drive"></i>](https://drive.google.com/drive/folders/1gyxX8SfYSV58EMgB5DbezA6cXNSZfw7y?usp=sharing)** |
| **2nd December** |
| 15:00 |  **[Zhengzheng Zhou](/authors/zhou/)**  |  Extreme storm analysis and Machine learning applications for rainfall prediction in urban areas| **[<i class="fab fa-youtube"></i>](https://youtu.be/9c9rpPnLgMk)** | **<i class="fas fa-file-pdf"></i>** |
| **3rd December** |
| 16:30 |  **[Michael Maerker](/authors/maerker/)**  |  Integrated Soil Erosion Assessment: Concepts, Methods and Applications| **[<i class="fab fa-youtube"></i>](https://youtu.be/asvJ60z0xNY)** | **<i class="fas fa-file-pdf"></i>** |
| 18:00 |  **[Andrey Zhidkin](/authors/zhidkin/)**  |  Historical reconstruction and forecast of soil cover degradation based on erosion modeling and field soil survey data| **[<i class="fab fa-youtube"></i>](https://youtu.be/asvJ60z0xNY)** | **<i class="fas fa-file-pdf"></i>** |
| **4th December** |
|Sunday|||
| **5th December** |
| 16:30 |  **[Paolo Porto](/authors/porto/)**  | 137Cs traditional and re-sampling approaches to estimate soil erosion for different time scales| **[<i class="fab fa-youtube"></i>](https://youtu.be/B2ian7Gmodc)** | **<i class="fas fa-file-pdf"></i>** |
| 18:00 |  **[Anatoly Tsyplenkov](/authors/tsyplenkov/)**  | Soil erosion modeling in R (workshop)| **[<i class="fab fa-youtube"></i>](https://youtu.be/B2ian7Gmodc)** | **<i class="fas fa-file-pdf"></i>** |
| **6th December** |
| 16:30 |  **[Seyed Hamidreza Sadeghi](/authors/sadeghi/)**  |  Necessity of the Watershed Health Assessment in Hydrology| **[<i class="fab fa-youtube"></i>](https://youtu.be/APXqWAVuunU)** | **<i class="fas fa-file-pdf"></i>** |
